var searchData=
[
  ['table_20of_20contents_0',['Table Of Contents',['../md_README.html#autotoc_md26',1,'']]],
  ['tail_20entity_1',['Predict Tail Entity',['../md_seed__embeddings_2OpenKE_2README.html#autotoc_md64',1,'']]],
  ['taken_2',['Time Taken',['../md_experiments_2README.html#autotoc_md23',1,'']]],
  ['test_20oracle_3',['Generate Test Oracle',['../md_docs_2version__upgrade__process.html#autotoc_md9',1,'']]],
  ['test_20suite_4',['Test suite',['../md_src_2test-suite_2README.html',1,'']]],
  ['testing_5',['Testing',['../md_seed__embeddings_2OpenKE_2README.html#autotoc_md60',1,'']]],
  ['the_20data_6',['Preprocesing the data',['../md_docs_2version__upgrade__process.html#autotoc_md7',1,'']]],
  ['the_20embedding_20matrix_7',['Getting the embedding matrix',['../md_seed__embeddings_2OpenKE_2README.html#autotoc_md68',1,'']]],
  ['the_20ir2vec_20binary_8',['Compile the IR2Vec binary',['../md_docs_2version__upgrade__process.html#autotoc_md4',1,'']]],
  ['the_20triplets_9',['The triplets',['../md_seed__embeddings_2README.html#autotoc_md80',1,'Preprocessing the triplets'],['../md_seed__embeddings_2README.html#autotoc_md76',1,'Steps to collect the triplets']]],
  ['thread_20coarsening_10',['Thread Coarsening',['../md_experiments_2README.html#autotoc_md19',1,'']]],
  ['time_20taken_11',['Time Taken',['../md_experiments_2README.html#autotoc_md23',1,'']]],
  ['to_20collect_20the_20triplets_12',['Steps to collect the triplets',['../md_seed__embeddings_2README.html#autotoc_md76',1,'']]],
  ['to_20generate_20embeddings_13',['Training TransE to generate embeddings',['../md_seed__embeddings_2README.html#autotoc_md81',1,'']]],
  ['to_20generate_20seed_20embedding_20vocabulary_14',['Files used to generate Seed Embedding Vocabulary',['../md_seed__embeddings_2README.html#autotoc_md77',1,'']]],
  ['to_20generate_20seed_20embedding_20vocabulary_15',['Step 3: Training TransE to generate seed embedding vocabulary',['../md_seed__embeddings_2README.html#autotoc_md78',1,'']]],
  ['to_20run_16',['To Run',['../md_experiments_2README.html#autotoc_md17',1,'Steps to Run'],['../md_experiments_2README.html#autotoc_md20',1,'Steps to Run']]],
  ['train_20models_17',['Step 4: Train models',['../md_seed__embeddings_2OpenKE_2README.html#autotoc_md59',1,'']]],
  ['training_18',['Training',['../md_docs_2version__upgrade__process.html#autotoc_md5',1,'Generating .ll files for re-training.'],['../md_seed__embeddings_2OpenKE_2README.html#autotoc_md57',1,'Step 2: Set configure parameters for training.'],['../md_docs_2version__upgrade__process.html#autotoc_md8',1,'Training'],['../md_seed__embeddings_2OpenKE_2README.html#autotoc_md55',1,'Training']]],
  ['training_20transe_20to_20generate_20embeddings_19',['Training TransE to generate embeddings',['../md_seed__embeddings_2README.html#autotoc_md81',1,'']]],
  ['training_20transe_20to_20generate_20seed_20embedding_20vocabulary_20',['Step 3: Training TransE to generate seed embedding vocabulary',['../md_seed__embeddings_2README.html#autotoc_md78',1,'']]],
  ['training_20triplets_21',['Generating Training Triplets',['../md_docs_2version__upgrade__process.html#autotoc_md6',1,'']]],
  ['transd_22',['TransD',['../classmodels_1_1TransD_1_1TransD.html',1,'models::TransD']]],
  ['transe_23',['TransE',['../classmodels_1_1TransE_1_1TransE.html',1,'models::TransE']]],
  ['transe_20to_20generate_20embeddings_24',['Training TransE to generate embeddings',['../md_seed__embeddings_2README.html#autotoc_md81',1,'']]],
  ['transe_20to_20generate_20seed_20embedding_20vocabulary_25',['Step 3: Training TransE to generate seed embedding vocabulary',['../md_seed__embeddings_2README.html#autotoc_md78',1,'']]],
  ['transh_26',['TransH',['../classmodels_1_1TransH_1_1TransH.html',1,'models::TransH']]],
  ['transr_27',['TransR',['../classmodels_1_1TransR_1_1TransR.html',1,'models::TransR']]],
  ['triple_28',['Triple',['../md_seed__embeddings_2OpenKE_2README.html#autotoc_md66',1,'Predict triple'],['../structTriple.html',1,'Triple']]],
  ['triple_20classification_29',['Triple Classification',['../md_seed__embeddings_2OpenKE_2README.html#autotoc_md62',1,'']]],
  ['triplets_30',['Triplets',['../md_docs_2version__upgrade__process.html#autotoc_md6',1,'Generating Training Triplets'],['../md_seed__embeddings_2README.html#autotoc_md80',1,'Preprocessing the triplets'],['../md_seed__embeddings_2README.html#autotoc_md75',1,'Step 2: Generating Triplets'],['../md_seed__embeddings_2README.html#autotoc_md76',1,'Steps to collect the triplets']]],
  ['tt_20ir2vec_20tt_31',['Step 1: Building &lt;tt&gt;ir2vec&lt;/tt&gt;',['../md_seed__embeddings_2README.html#autotoc_md74',1,'']]]
];
